---
abstract: 'Perl extension for creating a television station'
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires:
  Data::Dumper: 0
  Test::MockObject: 0
  Test::MockObject::Extends: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-PlaybackMachine
requires:
  AppConfig: 0
  Carp: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  DateTime::TimeZone::UTC: 0
  Exporter: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::Temp: 0
  File::stat: 0
  FindBin: 0
  Getopt::Long: 0
  IO::Dir: 0
  Image::Imlib2: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Moo: 0
  Moo::Role: 0
  POE: 0
  POE::Kernel: 0
  POE::Session: 0
  POSIX: 0
  SQL::Translator: 0.11016
  Text::CSV: 0
  Time::Duration: 0
  Types::Standard: 0
  Video::Xine: 0
  Video::Xine::Event: 0
  Video::Xine::Stream: 0
  Video::Xine::Util: 0
  X11::FullScreen: 0
  autodie: 0
  base: 0
  constant: 0
  perl: v5.10.0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  homepage: https://github.com/stephenenelson/video-playbackmachine
  repository: https://github.com/stephenenelson/video-playbackmachine.git
version: 0.09
