---
abstract: 'Perl extension for creating a television station'
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-PlaybackMachine
requires:
  AppConfig: 0
  DBD::Pg: 0
  DBI: 0
  Date::Manip: 0
  Image::Imlib2: 0
  Log::Log4perl: 0
  POE: 0
  Test::MockObject: 0
  Time::Duration: 0
  Video::Xine: 0.14
  X11::FullScreen: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Video-PlaybackMachine
  homepage: https://github.com///github.com/stephenenelson/video-playbackmachine/wiki
  repository: git://github.com///github.com/stephenenelson/video-playbackmachine.git
version: 0.08
